### ISSUE TITLE
CentOS to "Rocky" migrations.

### ISSUE THREAD

**Issue by sargenthp** [rocky-linux/rocky#11]
I am assuming to switch between CentOS and "Rocky" would be the same as going between RHEL and CentOS.  Swap out something like 12 packages, clean yum's DBs, and done.

Found this older article for RHEL/CentOS 6...  https://negativo17.org/converting-system-between-rhel-and-centos/

**Comment by AbelLykens** [comment]
We could get some inspiration from https://linux.oracle.com/switch/centos2ol.sh

**Comment by N3WWN** [comment]
I've not performed a CentOS -> OL migration, but I don't think it's going to be quite as easy as the RHEL -> CentOS migrations that I'm intimately familiar with.  

The versioning of some of the CentOS packages just slightly higher than the same RHEL-published package so that a `yum update` after switching repos results in packages being replaced.  

If OL does the same trick so that folks can migrate from CentOS to OL, then we should to take that into account so that the Rocky packages can be versioned slightly higher still, enabling migration to Rocky from RHEL/CentOS/OL.

**Comment by cfelder** [comment]
> The versioning of some of the CentOS packages just slightly higher than the same RHEL-published package so that a `yum update` after switching repos results in packages being replaced.

Usually you will use

``dnf distro-sync``

after switching repos. You don't care about higher/lower versions though.

**Comment by N3WWN** [comment]
@cfelder Personally, I've not used distro-sync because I haven't needed it and there always seemed to be a possibility of downgrading custom patched packages by mistake.  I should see if that's still the case... 🤔

**Comment by cfelder** [comment]
@N3WWN I agree that you may downgrade when using ``distro-sync`` but what you want to have is, basically the latest available version in the new distros repositories. If you have custom patches packages, I would rebuild them against the new repositories anyway, but you can keep your custom repo activated as well and if your package has the most recent version number it would not get overwritten.

**Comment by N3WWN** [comment]
@cfelder Sadly, we don't control how our customers distribute patches.  Some of them don't have a custom repo that they use to install custom patched packages.  They will copy the RPM to the system and install locally.

**Comment by greg-hellings** [comment]
Anyone in a scenario with custom packages should make use of the exclude functionality in the yum/dnf repo files to mask versions that might come from the upstream vendor and overwrite them. I would suggest pointing customers to configuring that everytime they overlay a package.

**Comment by N3WWN** [comment]
@greg-hellings Definitely.  We encourage using features like versionlock or excludes, but I never assume they're doing it.
