### ISSUE TITLE
Readme - alternative

### ISSUE THREAD

**Issue by mattwelke** [rocky-linux/rocky#113]
In the readme there is:

> A solid, stable, and transparent alternative for production environments, developed by the community for the community.

What is this an alternative to? I'm trying to wrap my head around what's going on in this space still. Is it an alternative to RHEL for those who don't want to pay and are okay without paid support? An alternative to CentOS Stream because they want something more stable? Or an alternative to Ubuntu because x? (I'm actually not really sure why one would use the old CentOS over Ubuntu)

**Comment by magicdrums** [comment]
I am not very clear if you are very aware of what is happening with CentOS since so far we all know that RedHat has never said that it is a production operating system, but many of us are affected by this decision which until many years ago we used a distribution that is really stable in production systems as CentOS has carried it so far with this. What I want to explain is that RockyLinux will be our migration alternative for people who use CentOS as productive systems.

I hope this answers your question.

**Comment by popeyesadley** [comment]
Donthing

**Comment by popeyesadley** [comment]
Milestone
