### ISSUE TITLE
DWM as Default

### ISSUE THREAD

**Issue by NicTanghe** [rocky-linux/rocky#57]
Dear community,

I would like to put this out here fast and soon.
Seeing that all standard desktops are basically unnecessary bloat that open doors to instability.
Especially gnome being a piece of rubbish.

I would very much like to have a window manager (not i3 or awesome because they are also rubbish)
as an option on install.

I understand the standard response is if you want something special just do it yourself.
but honestly doing it yourself every single time is very time consuming and having it there as a selectable default would be gr8. Im personally a verry big fan of instantos as generally sensible defaults are more important then people realise.

**Comment by nmusatti** [comment]
Rocky Linux is meant to be an exact copy of the upstream distribution, so it is not the place to ask for features that are not present there. Your best bet today is to ensure that your window manager of choice is available either in the upstream distribution or in a trustworthy external repository, such as EPEL. From there it is not hard to build up a working workstation starting from a minimal installation.

**Comment by Aesirkony** [comment]
I would like to know what the reasons are for claiming that they are garbage. It would be interesting to see something that is not relative and subjective.

I don't think an implementation of that class is decided just because a person believes that an environment is garbage, without having specific and objective bases to support it.

additional if it is not a feature that can be inherited from centos I do not think it can be taken lightly.

**Comment by brianclemens** [comment]
RL will not deviate from the the upstream.
