### ISSUE TITLE
Is the name set in stone?

### ISSUE THREAD

**Issue by manngo** [rocky-linux/rocky#6]
Sorry, that’s a bad pun, but I wonder whether then name “Rocky” might also give the wrong impression, as in unstable?

I suppose “Bullwinkle” would only make things worse.

**Comment by rolandkoller** [comment]
Just my personal opinion: A lot of post on social media etc. seam to share the concerns of @manngo. I really like the name. Its catchy, and has a better sound to it then _CentOS_. Rocky is rock solid!

**Comment by brokerka** [comment]
For me, sounds better, and simply:  "Enterprise Linux"

**Comment by SergeyUV** [comment]
Just my personal opinion.  The name of CentOS fork should sound very close to "CentOS". For example "SimpOS".  (Simp[le]OS)

**Comment by shiz0** [comment]
Initially the name sounded bit weird to me as well and I thought that https://github.com/Open-Enterprise-OS/oeos was way better suited.
But having learned that naming it "Rocky" is actually a tribute to one of the original co-founders who passed away(?), I think it's actually a really nice name!
https://github.com/hpcng/rocky/issues/2#issuecomment-742048445

**Comment by novmar** [comment]
Hello, what  about some like Rocosky, or RocentKy ? it is unique on google, and have little connection to original CentOS, and to Rocky. I prefer some nonexistent word, to have better search  resoults.

**Comment by pawlowskatze** [comment]
While I feel "Rocky Linux" isn't that bad, there is some ambiguosity with RockLinux and also "Rocky" either makes me think of the movie or a small funny dog's name, although I do understand where "Rocky" comes from.

However... a quick translate of "rocky" (adjective) gives us some nice play on words and meanings though:
For example, in French: "rocheux" -> can be made up to form roche-ux (like "Lin-ux") and isn't too far from "rock"-ux

Just my 2ct.
Excuse my French (and thus, yet another pun)

**Comment by swaroopchirayinkil** [comment]
This time no mistakes, the knowledge hard work, and unity must be preserved from all kinds of corporates greed.

**Comment by N3WWN** [comment]
Just throwing my $0.02 into the crowd:  Rock Enterprise Linux aka RockELinux

**Comment by mcen1** [comment]
The name is fine. Kudos for paying tribute.

**Comment by geiam** [comment]
42PlanOS  "the answer to everything"

**Comment by Lektonic** [comment]
Well, what if it were to be called RMG Linux or RMG-OS? That might come across as more "Professional" which is an issue several people seem to have with the name thus far. (The RMG stands for Rocky McGaugh) Then you keep the tribute, while also getting that slightly more professional feel that some might need to convince their Boss's Boss's Boss to switch from CentOS.

You can also have it called Rocky since the full Distro Name could be Rocky McGaugh OS or Rocky McGaugh Linux. That might give you the best of both. Or you could take it a step further and make Rocky and RMG Linux slightly different flavors.

**Comment by bp85** [comment]
How about RSEL - Rock(y) Solid Enterprise Linux?

**Comment by theCMack** [comment]
RLinux, gives tribute to Rocky as well as the name suggest "Our Linux", not IBM's.

**Comment by lulol** [comment]
CentaurOS

**Comment by robertjskelton** [comment]
Rocky Enterprise Linux, or REL. Easy to pronounce

**Comment by runiq** [comment]
Going off this thread, BikeshedOS.

**Comment by rick-masters** [comment]
With regards to the name "Rocky Linux", I'd just like to point out this quote from the Linux Foundation:

`If you plan to market a Linux-based product or service to the public using a trademark that includes the element “Linux,” such as “Super Dooper Linux” or “Real Time Linux Consultants” you are required to apply for and obtain a sublicense from the Linux Foundation. This is true whether or not you apply to register your trademark with a government.
`
https://www.linuxfoundation.org/about/linux-mark/

I am not affiliated with the foundation and I am not a lawyer but I hope implications of this are considered.
It seems something like RockyOS would not have this issue.

**Comment by mo-g** [comment]
I like the idea of a tribute to a passed developer, but I think people raise some valid concerns in both the uniqueness (ROCKS Clusters, Rock Linux,  Bedrock Linux) as well as the "explain to management" marketing worry. I think it certainly merits careful reconsideration, even if the end decision is the same.

That said, "no-one agrees on a band name" is the biggest killer of nascent rock bands, so just rolling with Rocky has merit beyond the tribute.

**Comment by mcen1** [comment]
If the name is what prevents your pitch from working with management, the problem is your pitch, not the name.

**Comment by alf10242048** [comment]
Maybe CEL
Community Enterprise Linux

**Comment by mo-g** [comment]
> If the name is what prevents your pitch from working with management, the problem is your pitch, not the name.

Or the problem is your management. Unfortunately, the fact that it's stupid doesn't make it untrue. Not an issue with my management, but I've worked plenty of places where it would have been.

**Comment by mcen1** [comment]
> > If the name is what prevents your pitch from working with management, the problem is your pitch, not the name.
> 
> Or the problem is your management. Unfortunately, the fact that it's stupid doesn't make it untrue. Not an issue with my management, but I've worked plenty of places where it would have been.

I feel your pain. Inept management is a fact of life.

However, a bad pitch is a pitch that fails to move the audience. CentOS's position in the product release cycle was very advantageous, I think it was advantageous so much so that a bad manager could grasp the benefits if they were explained correctly. If my pitch included these benefits and didn't move a manager, then I would blame myself for not understanding management's priorities correctly.

Open source is notorious for dubiously named tools... one might even take the "cent" in "CentOS" to mean 1 cent, or cheap. It's all marketing and truly doesn't matter given the advantages of the product itself. One person's "great suggestion" here would be an awful suggestion in someone else's org.

The point is also made moot by explaining it's named in memoriam for the founder. I doubt that line of questioning would go much farther than that once it's made known.

**Comment by gmkurtzer** [comment]
Sublicense from the LF has been requested.

Nobody ever will happy with a name. Sorry for those who don't like it. Unless I'm forced to use a different name, the existing name means something to the project.

Also please note, not everyone liked CentOS either. The amount of conversations which arose speaking about "how it will sound to management" was unnerving as was comments about it being worth a "cent" among other things.

Rocky Linux will grow on people, just like CentOS did.

**Comment by rick-masters** [comment]
Thanks for responding regarding the trademark license. Even if it is just routine I think it was worth airing.
As far as I am concerned I think this issue has been sufficiently addressed.
