### ISSUE TITLE
Add menu language

### ISSUE THREAD

**Issue by ErickRock** [rocky-linux/rocky#99]
Hello developer friends.

I am a systems development student and open-source enthusiast. I would like to contribute in some way to the project.

I created a menu at the end of readme.md, where you can browse the documentation between different languages. Follow the example below.
If you have any advice so that I can contribute more, please feel free.

# Preview of changes

## Read in other languages 

| Country | Language |
| -------|------|
Czech | [cs_CZ](/locales/README.cs_CZ.md)
German | [de_DE](/locales/README.de_DE.md)
English  | [en_US](/locales/README.en_US.md)
Spanish | [es_ES](/locales/README.es_ES.md)
French | [fr_FR](/locales/README.fr_FR.md)
Italian | [it_IT](/locales/README.it_IT.md)
Japanese | [ja_JP](/locales/README.ja_JP.md)
Korean | [ko_KR](/locales/README.ko_KR.md)
Portuguese (Brazilian) | [pt_BR](/locales/README.pt_BR.md) 
Russian | [ru_RU](/locales/README.ru_RU.md)
Swedish | [sv_SE](/locales/README.sv_SE.md)
Turkish | [tr_TR](/locales/README.tr_TR.md)
Chinese (Simplified) | [zh_CN](/locales/README.zh_CN.md)
Chinese (Traditional) | [zh_TW](/locales/README.zh_TW.md)

**Comment by Addvilz** [comment]
@ErickRock [flags are not languages](http://www.flagsarenotlanguages.com). Please, don't use flags to indicate languages - instead, use the language name in it's native form, for example, Español for Spanish. 

You have already used the flag of Peoples Republic of China for traditional Chinese - a writing where Republic of China flag would be more illustrative, although both are wrong, because - flags are not languages.

**Comment by ErickRock** [comment]
@Addvilz Thank you for your help! I'm going to do that right now.

**Comment by brianclemens** [comment]
Closed #99
> Thank you for your interest in contributing to Rocky Linux. This request would make adding languages even more burdensome, so I will not be merging it. Development on the website is a better place for your efforts. Please see the #rocky-www channel on Slack.
